services:
  - type: web
    name: e-pautas
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: "false"

      - key: APP_KEY
        generateValue: true

      - key: LOG_CHANNEL
        value: stderr

      - key: DB_CONNECTION
        value: sqlite

      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite

      - key: SESSION_DRIVER
        value: file

      - key: CACHE_STORE
        value: file

      - key: QUEUE_CONNECTION
        value: sync
